"""Notebook reporting helpers for dataset-level research review artifacts."""

from credit_risk_fs.reporting.notebook_report import (
    load_best_runs,
    load_dataset_report_inputs,
    load_dataset_snapshot,
    load_drift_table,
    load_final_comparison,
    load_run_artifacts,
    load_semantic_coverage_table,
    load_split_summary,
    load_stability_table,
    load_time_bucket_summary,
    plot_bad_rate_by_time,
    plot_dev_oot_split_diagnostics,
    plot_drift_vs_performance,
    plot_metric_leaderboard,
    plot_observation_count_by_time,
    plot_runtime_tradeoff,
    plot_semantic_coverage,
    plot_stability_vs_performance,
    summarize_clip_validation_placeholder,
    summarize_dataset_findings,
    summarize_split_rationale,
)

__all__ = [
    "load_best_runs",
    "load_dataset_report_inputs",
    "load_dataset_snapshot",
    "load_drift_table",
    "load_final_comparison",
    "load_run_artifacts",
    "load_semantic_coverage_table",
    "load_split_summary",
    "load_stability_table",
    "load_time_bucket_summary",
    "plot_bad_rate_by_time",
    "plot_dev_oot_split_diagnostics",
    "plot_drift_vs_performance",
    "plot_metric_leaderboard",
    "plot_observation_count_by_time",
    "plot_runtime_tradeoff",
    "plot_semantic_coverage",
    "plot_stability_vs_performance",
    "summarize_clip_validation_placeholder",
    "summarize_dataset_findings",
    "summarize_split_rationale",
]
