dataset_name: lendingclub_v2
data_dir: data/lendingclub_v2/processed
description_path: data/lendingclub_v2/metadata/columns_description.csv
results_dir: results
dev_start_day: -1795
oot_start_day: -1065
oot_end_day: -730
excluded_feature_columns:
  - TARGET
  - recent_decision
  - issue_d
  - loan_status
time_col: recent_decision
preprocessor_kwargs:
  cat_min_frequency: 50
